spring:
  application:
    name: Spring Boot demo users api
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:9876/users_db
    username: test_user
    password: test_password
  jpa:
    show-sql: true
  flyway:
    baseline-on-migrate: true
    create-schemas: false
    schemas: public

server:
  port: 8080
  servlet:
    session:
      timeout: 5m
    context-path: /api

logging:
  level:
    root: info
